# Generated by Django 6.0.2 on 2026-02-25 16:47

import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archives', '0005_archive_audio_url_archive_document_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LorePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content_json', models.JSONField(blank=True, help_text='Block-based content using Editor.js', null=True)),
                ('legacy_content', models.TextField(blank=True, help_text='Legacy HTML content')),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, help_text='External URL for image streaming')),
                ('video_url', models.URLField(blank=True, help_text='External URL for video streaming or YouTube embed')),
                ('audio_url', models.URLField(blank=True, help_text='External URL for audio streaming')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='lore/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size])),
                ('featured_video', models.FileField(blank=True, null=True, upload_to='lore/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg', 'mov']), core.validators.validate_video_size])),
                ('featured_audio', models.FileField(blank=True, null=True, upload_to='lore/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'm4a']), core.validators.validate_audio_size])),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('original_author', models.CharField(blank=True, help_text='For historical authors', max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('pending_approval', models.BooleanField(default=False, help_text='Post is pending admin approval')),
                ('is_rejected', models.BooleanField(default=False, help_text='Set to true if admin rejects the post')),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lore_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Select a category, e.g., Folktale, Proverb', limit_choices_to={'type': 'lore'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lore_posts', to='archives.category')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_published', 'is_approved', '-created_at'], name='lore_pub_date_idx')],
            },
        ),
    ]
