# Generated by Django 6.0.3 on 2026-05-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0002_add_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lorepost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
