# Generated by Django 5.1.4 on 2026-01-28 17:44

import core.validators
import django.core.validators
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveSmallIntegerField(help_text='Order of this item (1-5)')),
                ('item_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio')], help_text='Type of this item', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='archives/items/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size])),
                ('video', models.FileField(blank=True, null=True, upload_to='archives/items/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg', 'mov']), core.validators.validate_video_size])),
                ('audio', models.FileField(blank=True, null=True, upload_to='archives/items/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'm4a']), core.validators.validate_audio_size])),
                ('document', models.FileField(blank=True, null=True, upload_to='archives/items/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt']), core.validators.validate_document_size])),
                ('caption', models.CharField(blank=True, help_text='Caption for this item', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Description for this item')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=255)),
            ],
            options={
                'verbose_name': 'Archive Item',
                'verbose_name_plural': 'Archive Items',
                'ordering': ['item_number'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Bio or description of the author')),
                ('image', models.ImageField(blank=True, null=True, upload_to='authors/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required: Archive title', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title', max_length=255, null=True, unique=True)),
                ('description', models.TextField(help_text='Required: Detailed description (plain text)')),
                ('archive_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio')], help_text='Required: Type of archive', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='For image-type archives (max 5MB)', null=True, upload_to='archives/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size])),
                ('video', models.FileField(blank=True, help_text='For video-type archives (max 50MB)', null=True, upload_to='archives/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg', 'mov']), core.validators.validate_video_size])),
                ('document', models.FileField(blank=True, help_text='For document-type archives (max 10MB)', null=True, upload_to='archives/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt']), core.validators.validate_document_size])),
                ('audio', models.FileField(blank=True, help_text='For audio-type archives (max 10MB)', null=True, upload_to='archives/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'm4a']), core.validators.validate_audio_size])),
                ('featured_image', models.ImageField(blank=True, help_text='Thumbnail for videos/audio (optional, max 5MB)', null=True, upload_to='archives/featured/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size])),
                ('caption', models.CharField(blank=True, default='', help_text='Caption for the archive', max_length=500)),
                ('copyright_holder', models.CharField(blank=True, default='', help_text='Copyright holder (displays small after caption)', max_length=255)),
                ('original_url', models.URLField(blank=True, default='', help_text='Original URL from source museum/collection')),
                ('original_identity_number', models.CharField(blank=True, default='', help_text='Museum catalog/identity number', max_length=100)),
                ('item_count', models.PositiveSmallIntegerField(default=1, help_text='Number of items in this archive (1-5)')),
                ('alt_text', models.CharField(blank=True, default='', help_text='Required for images: Alt text for accessibility', max_length=255)),
                ('original_author', models.CharField(blank=True, help_text='Optional: Original photographer/creator (e.g., Northcote Thomas). Will auto-link to Author profile if match exists.', max_length=255)),
                ('date_created', models.DateField(blank=True, help_text='Optional: Exact date if known', null=True)),
                ('circa_date', models.CharField(blank=True, help_text="Optional: Approximate date (e.g., 'c1910', 'around 1910s')", max_length=100)),
                ('location', models.CharField(blank=True, help_text='Optional: Where the photo/artifact was taken/found', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval status')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Archives',
                'ordering': ['-created_at'],
            },
        ),
    ]
