# Generated by Django 5.2.10 on 2026-02-06 07:50

import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Bio or description of the author')),
                ('image', models.ImageField(blank=True, null=True, upload_to='authors/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('archive', 'Archive'), ('insight', 'Insight')], default='archive', help_text='Is this for Archives or Insights?', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required: Archive title', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title', max_length=255, null=True, unique=True)),
                ('description', models.TextField(help_text='Required: Detailed description (plain text)')),
                ('archive_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio')], help_text='Required: Type of archive', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='For image-type archives (max 5MB)', null=True, upload_to='archives/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size])),
                ('video', models.FileField(blank=True, help_text='For video-type archives (max 50MB)', null=True, upload_to='archives/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg', 'mov']), core.validators.validate_video_size])),
                ('document', models.FileField(blank=True, help_text='For document-type archives (max 10MB)', null=True, upload_to='archives/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt']), core.validators.validate_document_size])),
                ('audio', models.FileField(blank=True, help_text='For audio-type archives (max 10MB)', null=True, upload_to='archives/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'm4a']), core.validators.validate_audio_size])),
                ('featured_image', models.ImageField(blank=True, help_text='Thumbnail for videos/audio (optional, max 5MB)', null=True, upload_to='archives/featured/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size])),
                ('caption', models.CharField(blank=True, default='', help_text='Caption for the archive', max_length=500)),
                ('copyright_holder', models.CharField(blank=True, default='', help_text='Copyright holder (displays small after caption)', max_length=255)),
                ('original_url', models.URLField(blank=True, default='', help_text='Original URL from source museum/collection')),
                ('original_identity_number', models.CharField(blank=True, default='', help_text='Museum catalog/identity number', max_length=100)),
                ('item_count', models.PositiveSmallIntegerField(default=1, help_text='Number of items in this archive (1-5)')),
                ('alt_text', models.CharField(blank=True, default='', help_text='Required for images: Alt text for accessibility', max_length=255)),
                ('original_author', models.CharField(blank=True, help_text='Optional: Original photographer/creator (e.g., Northcote Thomas). Will auto-link to Author profile if match exists.', max_length=255)),
                ('date_created', models.DateField(blank=True, help_text='Optional: Exact date if known', null=True)),
                ('circa_date', models.CharField(blank=True, help_text="Optional: Approximate date (e.g., 'c1910', 'around 1910s')", max_length=100)),
                ('location', models.CharField(blank=True, help_text='Optional: Where the photo/artifact was taken/found', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval status')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, help_text='Link to a full author profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives', to='archives.author')),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'type': 'archive'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.category')),
            ],
            options={
                'verbose_name_plural': 'Archives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveSmallIntegerField(help_text='Order of this item (1-5)')),
                ('item_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio')], help_text='Type of this item', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='archives/items/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size])),
                ('video', models.FileField(blank=True, null=True, upload_to='archives/items/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg', 'mov']), core.validators.validate_video_size])),
                ('audio', models.FileField(blank=True, null=True, upload_to='archives/items/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'm4a']), core.validators.validate_audio_size])),
                ('document', models.FileField(blank=True, null=True, upload_to='archives/items/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt']), core.validators.validate_document_size])),
                ('caption', models.CharField(blank=True, help_text='Caption for this item', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Description for this item')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=255)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='archives.archive')),
            ],
            options={
                'verbose_name': 'Archive Item',
                'verbose_name_plural': 'Archive Items',
                'ordering': ['item_number'],
                'constraints': [models.UniqueConstraint(fields=('archive', 'item_number'), name='unique_archive_item_number')],
            },
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['is_approved', '-created_at'], name='arch_approved_date_idx'),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['archive_type', 'is_approved'], name='arch_type_approved_idx'),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['category', 'is_approved'], name='arch_cat_approved_idx'),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['slug'], name='arch_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['circa_date'], name='arch_circa_date_idx'),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['location'], name='arch_location_idx'),
        ),
    ]
