# Generated by Django 6.0.2 on 2026-02-09 12:57

from django.conf import settings
from django.db import migrations, models


def populate_sort_year(apps, schema_editor):
    import re
    Archive = apps.get_model('archives', 'Archive')
    for archive in Archive.objects.all():
        if archive.date_created:
            archive.sort_year = archive.date_created.year
        elif archive.circa_date:
            # Using the same logic as in the model save() method
            match = re.search(r'\b(1\d{3}|20\d{2})\b', str(archive.circa_date))
            if match:
                archive.sort_year = int(match.group(1))
            else:
                match = re.search(r'(\d{4})', str(archive.circa_date))
                if match:
                    archive.sort_year = int(match.group(1))
        
        if archive.sort_year:
            archive.save(update_fields=['sort_year'])


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='sort_year',
            field=models.IntegerField(blank=True, db_index=True, help_text='Numeric year for sorting purposes (auto-calculated)', null=True),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['sort_year'], name='arch_sort_year_idx'),
        ),
        migrations.RunPython(populate_sort_year, reverse_code=migrations.RunPython.noop),
    ]
