# Generated by Django 5.1.4 on 2026-01-28 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archiveitem',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='archives.archive'),
        ),
        migrations.AddField(
            model_name='archive',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Link to a full author profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives', to='archives.author'),
        ),
        migrations.AddField(
            model_name='archive',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.category'),
        ),
        migrations.AlterUniqueTogether(
            name='archiveitem',
            unique_together={('archive', 'item_number')},
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['is_approved', '-created_at'], name='arch_approved_date_idx'),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['archive_type', 'is_approved'], name='arch_type_approved_idx'),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['category', 'is_approved'], name='arch_cat_approved_idx'),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['slug'], name='arch_slug_idx'),
        ),
    ]
