# Generated by Django 5.2.9 on 2025-12-16 10:28

import archives.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='audio',
            field=models.FileField(blank=True, help_text='For audio-type archives (max 10MB)', null=True, upload_to='archives/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'm4a']), archives.models.validate_audio_size]),
        ),
        migrations.AlterField(
            model_name='archive',
            name='document',
            field=models.FileField(blank=True, help_text='For document-type archives (max 10MB)', null=True, upload_to='archives/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt']), archives.models.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='archive',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Thumbnail for videos/audio (optional, max 5MB)', null=True, upload_to='archives/featured/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), archives.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='archive',
            name='image',
            field=models.ImageField(blank=True, help_text='For image-type archives (max 5MB)', null=True, upload_to='archives/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), archives.models.validate_image_size]),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['is_approved', '-created_at'], name='arch_approved_date_idx'),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['archive_type', 'is_approved'], name='arch_type_approved_idx'),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['category', 'is_approved'], name='arch_cat_approved_idx'),
        ),
    ]
