# Generated by Django 5.2.10 on 2026-01-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='archiveitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='archiveitem',
            constraint=models.UniqueConstraint(fields=('archive', 'item_number'), name='unique_archive_item_number'),
        ),
    ]
