# Generated by Django 5.1.4 on 2026-01-25 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_add_slug_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Bio or description of the author')),
                ('image', models.ImageField(blank=True, null=True, upload_to='authors/')),
            ],
        ),
        migrations.AlterField(
            model_name='archive',
            name='original_author',
            field=models.CharField(blank=True, help_text='Optional: Original photographer/creator (e.g., Northcote Thomas). Will auto-link to Author profile if match exists.', max_length=255),
        ),
        migrations.AddField(
            model_name='archive',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Link to a full author profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives', to='archives.author'),
        ),
    ]
