# Generated by Django 5.2.10 on 2026-01-30 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_alter_archiveitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='archive',
            name='tags',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('archive', 'Archive'), ('insight', 'Insight')], default='archive', help_text='Is this for Archives or Insights?', max_length=20),
        ),
        migrations.AlterField(
            model_name='archive',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'archive'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.category'),
        ),
    ]
