# Generated by Django 5.1.4 on 2026-01-26 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_author_alter_archive_original_author_archive_author'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval status'),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['slug'], name='arch_slug_idx'),
        ),
    ]
