# Generated by Django 5.2.10 on 2026-01-31 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_alter_category_options_remove_archive_tags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['circa_date'], name='arch_circa_date_idx'),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['location'], name='arch_location_idx'),
        ),
    ]
