# Generated by Django 6.0.3 on 2026-03-08 17:17

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_archive_audio_url_archive_document_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authordescriptionrequest',
            name='proposed_image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/suggestions/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size]),
        ),
    ]
