# Generated by Django 6.0.2 on 2026-02-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_weekly_update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
