# Generated by Django 5.2.9 on 2026-01-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_message_msg_thread_read_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='msg_sender_date_idx'),
        ),
    ]
