# Generated by Django 6.0.2 on 2026-02-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigestQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('archive', 'New Archive'), ('insight', 'New Insight'), ('book', 'New Book Recommendation')], max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['processed', 'created_at'], name='digest_queue_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('email_type', models.CharField(choices=[('instant', 'Instant (approval, rejection, direct action)'), ('admin', 'Admin notification'), ('digest', 'Weekly digest')], default='instant', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['sent_at'], name='email_sent_date_idx'), models.Index(fields=['email_type', 'sent_at'], name='email_type_date_idx')],
            },
        ),
    ]
