# Generated by Django 5.1.4 on 2026-01-28 17:44

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('author', models.CharField(help_text='Book author(s)', max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(help_text='Recommendation title', max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('content_json', models.JSONField(blank=True, help_text='Block-based content using Editor.js', null=True)),
                ('legacy_content', models.TextField(blank=True, help_text='Legacy HTML content')),
                ('cover_image', models.ImageField(blank=True, help_text='Primary book cover (max 5MB)', null=True, upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size])),
                ('cover_image_back', models.ImageField(blank=True, help_text='Back cover (optional, max 5MB)', null=True, upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size])),
                ('alternate_cover', models.ImageField(blank=True, help_text='Alternate edition cover (optional, max 5MB)', null=True, upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('pending_approval', models.BooleanField(default=False, help_text='Pending admin approval')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When submitted for approval', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBookRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, help_text='Optional review comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Book Rating',
                'verbose_name_plural': 'User Book Ratings',
                'ordering': ['-created_at'],
            },
        ),
    ]
