# Generated by Django 5.2.10 on 2026-02-06 07:50

import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('author', models.CharField(help_text='Book author(s)', max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('external_url', models.URLField(blank=True, help_text='URL to book information or purchase page', max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(help_text='Recommendation title', max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('content_json', models.JSONField(blank=True, help_text='Block-based content using Editor.js', null=True)),
                ('legacy_content', models.TextField(blank=True, help_text='Legacy HTML content')),
                ('cover_image', models.ImageField(blank=True, help_text='Primary book cover (max 5MB)', null=True, upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size])),
                ('cover_image_back', models.ImageField(blank=True, help_text='Back cover (optional, max 5MB)', null=True, upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size])),
                ('alternate_cover', models.ImageField(blank=True, help_text='Alternate edition cover (optional, max 5MB)', null=True, upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('pending_approval', models.BooleanField(default=False, help_text='Pending admin approval')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When submitted for approval', null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBookRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, help_text='Optional review comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='books.bookrecommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Book Rating',
                'verbose_name_plural': 'User Book Ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bookrecommendation',
            index=models.Index(fields=['is_published', 'is_approved', '-created_at'], name='book_pub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='bookrecommendation',
            index=models.Index(fields=['added_by', 'is_published'], name='book_user_pub_idx'),
        ),
        migrations.AddConstraint(
            model_name='userbookrating',
            constraint=models.UniqueConstraint(fields=('book', 'user'), name='unique_user_book_rating'),
        ),
    ]
