# Generated by Django 6.0.2 on 2026-02-06 09:20

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrecommendation',
            name='alternate_cover',
        ),
        migrations.RemoveField(
            model_name='bookrecommendation',
            name='cover_image_back',
        ),
        migrations.AlterField(
            model_name='bookrecommendation',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Book cover image (max 5MB)', null=True, upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size]),
        ),
    ]
