# Generated by Django 5.1.4 on 2026-01-28 17:44

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecommendation',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookrecommendation',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='userbookrating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='books.bookrecommendation'),
        ),
        migrations.AddField(
            model_name='userbookrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookrecommendation',
            index=models.Index(fields=['is_published', 'is_approved', '-created_at'], name='book_pub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='bookrecommendation',
            index=models.Index(fields=['added_by', 'is_published'], name='book_user_pub_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbookrating',
            unique_together={('book', 'user')},
        ),
    ]
