# Generated by Django 5.2.9 on 2025-12-16 10:28

import books.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='alternate_cover',
            field=models.ImageField(blank=True, help_text='Alternate edition cover (optional, max 5MB)', null=True, upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), books.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='content_json',
            field=models.JSONField(blank=True, help_text='Block-based review content using Editor.js', null=True),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Primary book cover (max 5MB)', null=True, upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), books.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='cover_image_back',
            field=models.ImageField(blank=True, help_text='Back cover (optional, max 5MB)', null=True, upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), books.models.validate_file_size]),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['is_published', 'is_approved', '-created_at'], name='book_pub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['reviewer', 'is_published'], name='book_reviewer_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['rating', 'is_approved'], name='book_rating_idx'),
        ),
    ]
