# Generated by Django 5.2.10 on 2026-01-29 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbookrating',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userbookrating',
            constraint=models.UniqueConstraint(fields=('book', 'user'), name='unique_user_book_rating'),
        ),
    ]
