# Generated by Django 5.2.10 on 2026-01-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_userbookrating_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrecommendation',
            name='tags',
        ),
    ]
