# Generated by Django 6.0.3 on 2026-05-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookrecommendation_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecommendation',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
