# Generated by Django 4.2.25 on 2025-10-30 14:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_editorjs_fields.fields
import insights.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('archives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('content_json', django_editorjs_fields.fields.EditorJsJSONField(blank=True, help_text='Block-based content using Editor.js', null=True)),
                ('legacy_content', models.TextField(blank=True, help_text='Legacy HTML content')),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='insights/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), insights.models.validate_file_size])),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('image_caption', models.CharField(blank=True, help_text='Image caption with copyright/source info', max_length=500)),
                ('image_description', models.TextField(blank=True, help_text='Detailed image description')),
                ('copyright_info', models.CharField(blank=True, help_text='Copyright or image source', max_length=500)),
                ('submit_as_archive', models.BooleanField(default=True, help_text='Submit uploaded images as archives')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('pending_approval', models.BooleanField(default=False, help_text='Post is pending admin approval')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When post was submitted for approval', null=True)),
                ('posted_to_social', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='insights/uploads/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), insights.models.validate_file_size])),
                ('caption', models.CharField(help_text='Required: Caption with copyright/source', max_length=500)),
                ('description', models.TextField(help_text='Required: Image description')),
                ('alt_text', models.CharField(help_text='Alt text for accessibility', max_length=255)),
                ('archive_title', models.CharField(blank=True, max_length=255)),
                ('archive_type', models.CharField(default='image', max_length=20)),
                ('original_author', models.CharField(blank=True, help_text='e.g., Northcote Thomas', max_length=255)),
                ('date_created_field', models.DateField(blank=True, null=True)),
                ('circa_date', models.CharField(blank=True, help_text='e.g., c1910, around 1910s', max_length=100)),
                ('approved_as_archive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archive_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.category')),
                ('archive_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.archive')),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='insights.insightpost')),
            ],
        ),
        migrations.CreateModel(
            name='EditSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, help_text='Admin reason for rejection')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='insights.insightpost')),
                ('suggested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
