# Generated by Django 6.0.2 on 2026-02-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightpost',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='Set to true if admin rejects the post'),
        ),
        migrations.AddField(
            model_name='insightpost',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Internal reason for rejection'),
        ),
    ]
