# Generated by Django 5.1.4 on 2026-01-28 17:44

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archives', '0002_initial'),
        ('insights', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='editsuggestion',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insightpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insightpost',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='editsuggestion',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='insights.insightpost'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='archive_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.category'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='archive_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.archive'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='insight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='insights.insightpost'),
        ),
        migrations.AddIndex(
            model_name='insightpost',
            index=models.Index(fields=['is_published', 'is_approved', '-created_at'], name='insight_pub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='insightpost',
            index=models.Index(fields=['author', 'is_published'], name='insight_author_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='insightpost',
            index=models.Index(fields=['pending_approval'], name='insight_pending_idx'),
        ),
        migrations.AddIndex(
            model_name='editsuggestion',
            index=models.Index(fields=['post', 'is_approved', 'is_rejected'], name='suggestion_status_idx'),
        ),
    ]
