# Generated by Django 5.2.9 on 2025-12-16 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightpost',
            name='content_json',
            field=models.JSONField(blank=True, help_text='Block-based content using Editor.js', null=True),
        ),
        migrations.AddIndex(
            model_name='editsuggestion',
            index=models.Index(fields=['post', 'is_approved', 'is_rejected'], name='suggestion_status_idx'),
        ),
        migrations.AddIndex(
            model_name='insightpost',
            index=models.Index(fields=['is_published', 'is_approved', '-created_at'], name='insight_pub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='insightpost',
            index=models.Index(fields=['author', 'is_published'], name='insight_author_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='insightpost',
            index=models.Index(fields=['pending_approval'], name='insight_pending_idx'),
        ),
    ]
