# Generated by Django 5.2.10 on 2026-01-30 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_alter_category_options_remove_archive_tags_and_more'),
        ('insights', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insightpost',
            name='tags',
        ),
        migrations.AddField(
            model_name='insightpost',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a category for this insight', limit_choices_to={'type': 'insight'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='archives.category'),
        ),
    ]
