# Generated by Django 6.0.3 on 2026-03-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveanalysis',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='archiveanalysis',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='session',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='ai_chatsess_user_id_19e151_idx',
        ),
        migrations.DeleteModel(
            name='ArchiveAnalysis',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
