# Generated by Django 5.1.4 on 2026-01-28 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveanalysis',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='archives.archive'),
        ),
    ]
