# Generated by Django 5.2.10 on 2026-01-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveanalysis',
            name='analysis_type',
            field=models.CharField(choices=[('description', 'Image Description'), ('historical', 'Historical Context'), ('cultural', 'Cultural Significance'), ('translation', 'Text Translation'), ('artifact', 'Artifact Identification')], max_length=50),
        ),
    ]
